name: Build on Staging

on:
  push:
    branches: [ "staging" ]
  pull_request:
    branches: [ "staging" ]

jobs:
   deploy-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Staging
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_STAGING_KEY }}
          api-key: ${{ secrets.RENDER_API_KEY }}
