name: Build on QA

on:
  push:
    branches: [ "qa" ]
  pull_request:
    branches: [ "qa" ]

jobs:
   deploy-qa:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to QA
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_QA_KEY }}
          api-key: ${{ secrets.RENDER_API_KEY }}
